### ISSUE TITLE
能不能设置签到间隔，太快被腾讯限制

### ISSUE THREAD

**Issue by lukemin** [evilinsipid/QQ-Group-Check-in#3]
能不能设置签到间隔，太快被腾讯限制，一次只能签五个多了就会出现错误！

**Comment by xyang532** [comment]
已添加，可自行在文件里设置，我标注出来了

**Comment by lukemin** [comment]
谢谢，还有就是签到内容中 [签到] 这两个个字怎么取消？

**Comment by xyang532** [comment]
签到内容在py文件里我也注明了更改位置，仔细找一下哦

**Comment by lukemin** [comment]
不是这个 现在签到内容 **[签到]：自定义内容**， 能不能把[签到]也去掉，直接出自定义内容

**Comment by xyang532** [comment]
你看到的**[签到]**前缀其实是QQ自动加的，用来区分正常消息与签到消息

**Comment by lukemin** [comment]
明白了，再次谢谢您

**Comment by xyang532** [comment]
没事昂
