### ISSUE TITLE
全部签到完毕后，不退出。

### ISSUE THREAD

**Issue by lukemin** [evilinsipid/QQ-Group-Check-in#4]
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:06:47) [MSC v.1914 32 bit (Intel)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> 
 RESTART: C:\Users\Administrator\Desktop\QQ-Group-Check-in-master\qq3 - 副本.py 
{"cgicode":0,"retcode":0,"msg":"","data":{"sign_id":"1553214249340232"}}
{"cgicode":0,"retcode":0,"msg":"","data":{"sign_id":"1553214309668232"}}
{"cgicode":0,"retcode":0,"msg":"","data":{"sign_id":"1553214369156832"}}
{"cgicode":0,"retcode":0,"msg":"","data":{"sign_id":"1553214429144032"}}
{"cgicode":0,"retcode":0,"msg":"","data":{"sign_id":"1553214489723632"}}
{"cgicode":0,"retcode":0,"msg":"","data":{"sign_id":"1553214550139032"}}
{"cgicode":0,"retcode":0,"msg":"","data":{"sign_id":"1553214610101232"}}
{"cgicode":0,"retcode":0,"msg":"","data":{"sign_id":"1553214670693932"}}
{"cgicode":0,"retcode":0,"msg":"","data":{"sign_id":"1553214730017132"}}
{"cgicode":0,"retcode":0,"msg":"","data":{"sign_id":"1553214790762932"}}
{"cgicode":0,"retcode":0,"msg":"","data":{"sign_id":"1553214851933232"}}
{"cgicode":0,"retcode":0,"msg":"","data":{"sign_id":"1553214911856232"}}
{"cgicode":0,"retcode":0,"msg":"","data":{"sign_id":"1553214971838432"}}
{"cgicode":0,"retcode":0,"msg":"","data":{"sign_id":"1553215031993532"}}
{"cgicode":0,"retcode":0,"msg":"","data":{"sign_id":"1553215091384432"}}
{"cgicode":0,"retcode":0,"msg":"","data":{"sign_id":"1553215152983032"}}
{"cgicode":0,"retcode":0,"msg":"","data":{"sign_id":"1553215212194232"}}
{"cgicode":0,"retcode":0,"msg":"","data":{"sign_id":"1553215272262932"}}
{"cgicode":0,"retcode":0,"msg":"","data":{"sign_id":"1553215332532132"}}
>>>
能加上一个提示就好了

**Comment by xyang532** [comment]
这个最开始是我debug用的报文，而且其实一般都是用linux系统crontab来实现自动签到，这样就不会看到这个return。至于你说的提示是指什么呢？

**Comment by lukemin** [comment]
提示就是签到完毕什么的

**Comment by xyang532** [comment]
已更新
