### ISSUE TITLE
windows运行正常linux运行获取不到skey

### ISSUE THREAD

**Issue by guigui0326** [evilinsipid/QQ-Group-Check-in#5]
windows运行正常linux运行获取不到skey
![image](https://user-images.githubusercontent.com/30816908/55784992-3f25dc80-5ae4-11e9-9a0d-2285c8664c4b.png)

**Comment by xyang532** [comment]
没获取到skey说明cookies里不存在，这就很奇怪了
你尝试看看用

    for key in s.cookies.keys():
        print('%s: %s' % (key, s.cookies[key]))

替换

    skey = s.cookies['skey']

然后把其下边，到下个函数之前的代码行用

    '''
    这是多行注释，用三个单引号
    这是多行注释，用三个单引号 
    这是多行注释，用三个单引号
    '''

这种形式变为注释，运行一下看看当前cookies里到底是什么

**Comment by guigui0326** [comment]
只能拿到ptdrvs 不知道为什么感觉很奇怪


------------------ 原始邮件 ------------------
发件人: "evilinsipid"<notifications@github.com>;
发送时间: 2019年4月10日(星期三) 凌晨5:16
收件人: "evilinsipid/QQ-Group-Check-in"<QQ-Group-Check-in@noreply.github.com>;
抄送: "Firstmeet·初见"<1834537260@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [evilinsipid/QQ-Group-Check-in] windows运行正常linux运行获取不到skey (#5)




没获取到skey说明cookies里不存在，这就很奇怪了
 你尝试看看用
 for key in c.cookies.keys():     print('%s: %s' % (key, c.cookies[key]))  
替换
 skey= s.cookies['skey']  
然后把其下边，到下个函数之前的代码行用
 ''' 这是多行注释，用三个单引号 这是多行注释，用三个单引号  这是多行注释，用三个单引号 '''  
这种形式变为注释，运行一下看看当前cookies里到底是什么

**Comment by xyang532** [comment]
你可以对照看看pc端和linux端获取到的参数，如果ptdrvs等于skey或类似的话，把原代码改成

    skey = s.cookies['ptdrvs']

就行了

**Comment by muzhiyun** [comment]
同样
Windows10 1709专业版 python3.5.2下可正常运行  
Centos7.4+python3.6.6报错  

具体报错信息
```
root@VM_718_200_centos QQ-Group-Check-in-master]# python3.4 qq.py
Traceback (most recent call last):
  File "qq.py", line 116, in <module>
    main()
  File "qq.py", line 79, in main
    skey = s.cookies['skey']
  File "/usr/lib/python3.4/site-packages/requests/cookies.py", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File "/usr/lib/python3.4/site-packages/requests/cookies.py", line 399, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='skey', domain=None, path=None"
[root@VM_718_200_centos QQ-Group-Check-in-master]#
```

做过的尝试  
- 尝试将Centos上python版本更换为3.4，问题仍然存在
- 考虑过文件编码或者不同平台换行符问题，问题仍然存在
- 尝试在Win10的Linux子系统(即wsl ubuntu16.04 python3.6)中运行，运行正常
- 尝试将`skey = s.cookies['skey']`更换为`skey = s.cookies['ptdrvs']`后在Centos上运行，输出空行，具体如下
```
[root@VM_718_200_centos QQ-Group-Check-in-master]# python3.4 qq.py

[root@VM_718_200_centos QQ-Group-Check-in-master]# 
```

- 尝试按照(https://github.com/evilinsipid/QQ-Group-Check-in/issues/5#issuecomment-481443599)  修改脚本，修改后Windows和wsl子系统均报错，报错具体为
```
D:\node-v8.11.1-win-x64>python qq.py
Traceback (most recent call last):
  File "qq.py", line 116, in <module>
    main()
  File "qq.py", line 82, in main
    print('%s: %s' % (key, s.cookies[key]))
  File "D:\Program Files\Python35\lib\site-packages\requests\cookies.py", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File "D:\Program Files\Python35\lib\site-packages\requests\cookies.py", line 399, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='ETK', domain=None, path=None"

D:\node-v8.11.1-win-x64>
```
Centos输出
```
[root@VM_718_200_centos QQ-Group-Check-in-master]# python3.4 qq.py
confirmuin: 0
ptdrvs: TvRcLkTnpgYSJf5wEctLZhC6A-grXfFyots5bxHbcRw3029vfnrBkg__
ptvfsession: 761f1899844dd7022b9d2204ca1a16e8a1011f6e20db37dd670b181f619fcf123d52cb56e2c37de3056cb265e25260c1
ptisp: cn
Traceback (most recent call last):
  File "qq.py", line 115, in <module>
    main()
  File "qq.py", line 82, in main
    bkn = getBKN(skey)
NameError: name 'skey' is not defined
[root@VM_718_200_centos QQ-Group-Check-in-master]# 
```
- Windows平台修改为`skey = s.cookies['skey']`， Centos修改为`skey = s.cookies['ptdrvs']` 
 `print(skey)`对比输出结果  

Windows打印
```
D:\node-v8.11.1-win-x64>python qq.py
@hgKU9CZKM
签到执行完毕

D:\node-v8.11.1-win-x64>
```
  Centos打印
```
[root@VM_718_200_centos QQ-Group-Check-in-master]# python3.4 qq.py
uL4E52D*JzX-J55WafU3VIo4ouD9ADjHo36Bjo4MTUoIvZ0z39RLaw__

[root@VM_718_200_centos QQ-Group-Check-in-master]# 
```

**Comment by xyang532** [comment]
@muzhiyun 真是麻烦你了，做了这么多的尝试

之前的

    for key in s.cookies.keys():
        print('%s: %s' % (key, s.cookies[key]))

报错是由于

- 由于替换掉了`skey = s.cookies['skey']`导致后边的取值无法进行，当然这无伤大雅
- 经过我调试后发现，`s.cookies.keys()`取出的有些“键”无法取到相应的“键值”


所以现在转变一下思路，把`skey = s.cookies['skey']`替换为

    for key in s.cookies.keys():
        print('%s' % (key))

尝试看看取出键来进行对比

这是正常来说应该取出的键

    ETK
    confirmuin
    pt2gguin
    pt_recent_uins
    ptdrvs
    ptnick_xxxxxxx(xxx是qq号)
    ptvfsession
    superkey
    supertoken
    superuin
    RK
    ptcz
    ptisp
    skey
    uin

所以如果可以的话，你可以尝试看看在你那取出的键是什么

**Comment by muzhiyun** [comment]
感谢回复
  按最新方法修改之后测试
Centos输出
```
[root@VM_718_200_centos QQ-Group-Check-in-master]# python3.4 qq.py 
confirmuin
ptdrvs
ptisp
[root@VM_718_200_centos QQ-Group-Check-in-master]#
```
Windows输出
```
D:\node-v8.11.1-win-x64>python qq.py
ETK
confirmuin
pt2gguin
pt_recent_uins
ptdrvs
ptnick_***********
ptvfsession
superkey
supertoken
superuin
RK
ptcz
ptisp
skey
uin
D:\node-v8.11.1-win-x64>
```
看起来似乎Centos仍然存在问题，使用的Centos是腾讯云北京云服务器，考虑是不是网络问题，在多台机器上安装了环境进行测试，测试结果：

- **以下均正常**
    本地  Windows 10 
    本地 Linux子系统/wsl Ubuntu 16.04
    本地 VMware虚拟机 Centos7
    本地 Debian 9 

- **以下均失败**
    北京腾讯云Centos7
    香港腾讯云Ubuntu16.04
    香港谷歌GCE

看起来似乎与系统版本，Python版本无关，而与网络有关，似乎运行在远程服务器因为IP地址变化触发了QQ异地登录保护，在常登陆地的设备上使用一切正常，也许需要在README.md进行注明

**Comment by xyang532** [comment]
@muzhiyun 谢谢，完全忘了还有异地保护这玩意，一直把问题锁定在python身上，我会注明的

**Comment by fishSteak** [comment]
## windows10 专业版 python qq.py 运行错误 KeyError
PS C:\Users\Fish_Steak\QQgroup> python .\qq.py
Traceback (most recent call last):
  File ".\qq.py", line 112, in <module>
    main()
  File ".\qq.py", line 78, in main
    skey = s.cookies['skey']
  File "C:\Users\Fish_Steak\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\cookies.py", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File "C:\Users\Fish_Steak\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\cookies.py", line 399, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='skey', domain=None, path=None"

**Comment by fishSteak** [comment]
## windows python qq.py运行错误  KeyError: "name='skey', domain=None, path=None"
<code>
PS C:\Users\Fish_Steak\QQgroup> python.exe .\qq.py
Traceback (most recent call last):
  File ".\qq.py", line 112, in <module>
    main()
  File ".\qq.py", line 78, in main
    skey = s.cookies['skey']
  File "C:\Users\Fish_Steak\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\cookies.py", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File "C:\Users\Fish_Steak\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\cookies.py", line 399, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='skey', domain=None, path=None"
</code>
